struct TVertexInput
{
	float3 Position			: POSITION;
	float2 TexCoord			: TEXCOORD0;
};

struct TVertexOutput
{
	float2 TexCoord			: TEXCOORD0;
};

#ifdef VERTEX_SHADER

TVertexOutput GetVertexOutput(out float4 OutPosition, in TVertexInput VertexInput)
{
	OutPosition = float4(VertexInput.Position, 1);
	TVertexOutput VertexOutput;	
	VertexOutput.TexCoord = VertexInput.TexCoord;
	return VertexOutput;
}
#endif