struct TVertexInput
{
	float3 Position			: POSITION;
	float3 Normal			: NORMAL;
	float2 TexCoord			: TEXCOORD0;
};

struct TVertexOutput
{
	float2 TexCoord			: TEXCOORD0;
	float3 Normal			: TEXCOORD1;
	float3 PixelPosition	: TEXCOORD2;
};

#ifdef VERTEX_SHADER

float4 CalcOutPosition(in TVertexInput VertexInput)
{
	return mul(float4(VertexInput.Position, 1), ViewProjectionMatrix);
}

#endif