// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package server;

public final class Com_Stub
    extends java.rmi.server.RemoteStub
    implements common.ICom, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_login_0;
    private static java.lang.reflect.Method $method_ping_1;
    
    static {
	try {
	    $method_login_0 = common.ICom.class.getMethod("login", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_ping_1 = common.ICom.class.getMethod("ping", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Com_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of login(String, String)
    public dataset.User login(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_login_0, new java.lang.Object[] {$param_String_1, $param_String_2}, 8255974224146657066L);
	    return ((dataset.User) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of ping()
    public java.lang.String ping()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_ping_1, null, -5977121354941433790L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
